/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { I64 } from './i64';
import type { OrderDirection } from './orderDirection';

export type GetQueriesParams = {
  /**
   * Minimal duration of queries in milliseconds
   */
  minDurationMs?: number;
  /**
   * Worksheet id of the queries
   */
  worksheetId?: I64;
  /**
   * Queries offset
   * @minimum 0
   */
  offset?: number;
  /**
   * Queries limit
   * @minimum 0
   */
  limit?: number;
  /**
   * Queries search
   */
  search?: string;
  /**
   * Order by: id, worksheet_id, result_count, status, start_time (default), end_time, duration_ms
   */
  orderBy?: string;
  /**
   * Order direction: ASC, DESC (default)
   */
  orderDirection?: OrderDirection;
};
