/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { OrderDirection } from './orderDirection';

export type GetVolumesParams = {
  /**
   * Volumes offset
   * @minimum 0
   */
  offset?: number;
  /**
   * Volumes limit
   * @minimum 0
   */
  limit?: number;
  /**
   * Volumes search
   */
  search?: string;
  /**
   * Order by: volume_name, volume_type, created_at (default), updated_at
   */
  orderBy?: string;
  /**
   * Order direction: ASC, DESC (default)
   */
  orderDirection?: OrderDirection;
};
