/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * UI Router API
 * Defines the specification for the UI Catalog API
 * OpenAPI spec version: 1.0.2
 */
import type { AwsCredentials } from './awsCredentials';
import type { S3TablesVolumeEndpoint } from './s3TablesVolumeEndpoint';

export interface S3TablesVolume {
  arn: string;
  credentials: AwsCredentials;
  endpoint?: S3TablesVolumeEndpoint;
}
